### ISSUE TITLE
Geonames Labels

### ISSUE THREAD

**Issue by jsimic** [uoregon-libraries/digital-exhibits-spotlight#102]
Fix Geonames display. Some names display as the URI, others as text  

Working in the Doris Ulmann exhibits, some items imported from Oregon Digital are displaying the Region/Geonames URIs and not the labels.

This is a priority and is related to ticket #103

**Comment by lsat12357** [comment]
I looked at an example: https://expo.uoregon.edu/spotlight/doris-ulmann/catalog/df66wt68v
and then I looked at the edit page for the image on oregondigital:
https://oregondigital.org/ingest/oregondigital:df66wt68v/edit
and the problem is that the label was not fetched. Spotlight can't fetch labels, it gets the label from the solr record coming out of oregondigital.

**Comment by lsat12357** [comment]
I thought, btw, that I had set things up to NOT display a uri if no label was available, so there's still something for me to fix.

**Comment by jsimic** [comment]
Do we need to reindex the entire Ulmann collection in OD to fetch the labels and re-import all records, or can we do them individually? If we do need to do them en masse will the labels Leslie added persist or will they need to be re-added (I believe they were all added by Linda via spreadsheet)?

**Comment by lsat12357** [comment]
So all the things finally happened: although geonames labels are not being fetched at the moment, Ryan Wick gave me a workaround to set the labels manually; after a reindex on OD, ran a reindex of just the affected assets on spotlight, and fortunately I didn't overwhelm the service since I didn't think to run it via workers. I think your tags are ok, but let me know if they're not.
